#!/usr/bin/env bash

check_factor() {
    if [ $# -ne 1 ]; then
        echo "Usage: check_factor <result>"
        exit 1
    fi

    result=$1
    num1=$(echo "$result" | awk '{print $2}')
    num2=$(echo "$result" | awk '{print $3}')

    if [ "$num2" -gt "$num1" ]; then
        tmp=$num1
        num1=$num2
        num2=$tmp
    fi

    echo "$num1*$num2"
}

if [ $# -ne 1 ]; then
    echo 'Usage: rsa <file>'
    exit 1
else
    while read i; do
        result=$(factor "$i")
        check_factor "$result"
    done < "$1"
fi
